alias vi='nvim'
alias vim='nvim'
alias virtualenv='python3 -m virtualenv'
alias clip='xclip -selection c'
alias firefox='~/Apps/firefox/firefox'
alias visualizer='cava -p ~/.config/cava/config'
alias config='git --git-dir=/home/optixal/.dotfiles/ --work-tree=/home/optixal'
